/**
 * ビルドスクリプト
 * TypeScriptをGAS用にトランスパイルし、1つのファイルに連結する
 * 依存関係の順序を考慮して連結することでモジュール関連の問題を解消
 */
const esbuild = require("esbuild");
const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "dist");
const srcDir = path.join(__dirname, "src");

// ファイルの依存関係順（依存されるものが先）
const fileOrder = ["constants.ts", "auth.ts", "calendar.ts", "user.ts", "main.ts"];

async function build() {
  try {
    // distディレクトリを作成（なければ）
    if (!fs.existsSync(distDir)) {
      fs.mkdirSync(distDir, { recursive: true });
    }

    // 既存のファイルを削除
    const existingFiles = fs.readdirSync(distDir);
    for (const file of existingFiles) {
      if (file.endsWith(".js")) {
        fs.unlinkSync(path.join(distDir, file));
      }
    }

    // 各ファイルを個別にトランスパイル
    const transpiledParts = [];

    for (const filename of fileOrder) {
      const filepath = path.join(srcDir, filename);
      if (!fs.existsSync(filepath)) {
        console.warn(`Warning: ${filename} not found, skipping`);
        continue;
      }

      // esbuildで単一ファイルをトランスパイル
      const result = await esbuild.build({
        entryPoints: [filepath],
        write: false,
        format: "esm",
        target: "es2019",
        platform: "neutral",
        bundle: false, // バンドルしない（単一ファイルのトランスパイルのみ）
      });

      let content = result.outputFiles[0].text;

      // import文を削除（すでに連結されるため不要）
      content = content.replace(/^import\s+\{[\s\S]*?\}\s+from\s+["'][^"']+["'];?\s*$/gm, "");
      content = content.replace(/^import\s+.*?from\s+["'][^"']+["'];?\s*$/gm, "");
      content = content.replace(/^import\s+["'][^"']+["'];?\s*$/gm, "");

      // export文を削除
      // export function → function
      content = content.replace(/^export\s+(function|const|let|var|class|interface|type)/gm, "$1");
      // export { xxx };
      content = content.replace(/^export\s*\{[^}]*\};\s*$/gm, "");
      // export default
      content = content.replace(/^export\s+default\s+/gm, "");

      // __commonJSヘルパーとラッパーを削除
      content = content.replace(/^var __getOwnPropNames[\s\S]*?^\};$/gm, "");
      content = content.replace(/^var __commonJS[\s\S]*?^\};$/gm, "");
      content = content.replace(/^var require_main = __commonJS\(\{\s*"src\/main\.ts"\(\) \{/gm, "");
      content = content.replace(/^\s*\}\s*\}\);$/gm, "");
      content = content.replace(/^require_main\(\);$/gm, "");

      // main.tsの関数定義のインデントを修正（4スペースを削除）
      if (filename === "main.ts") {
        content = content.replace(/^    /gm, "");
      }

      // ファイルのセクションヘッダー
      const sectionHeader = `// ========== ${filename.replace(".ts", "")} ==========\n`;

      transpiledParts.push(sectionHeader + content.trim());
    }

    // すべてのパーツを連結
    const banner = "// Auto-generated by esbuild - DO NOT EDIT\n// This file is bundled from multiple TypeScript source files\n\n";
    let finalContent = banner + transpiledParts.join("\n\n");

    // 余分な空行を整理
    finalContent = finalContent.replace(/\n{3,}/g, "\n\n");

    const bundlePath = path.join(distDir, "bundle.js");
    fs.writeFileSync(bundlePath, finalContent);

    console.log("Build completed successfully!");
    console.log(`Output: ${bundlePath}`);
    console.log(`Files bundled: ${fileOrder.join(", ")}`);
  } catch (error) {
    console.error("Build failed:", error.message);
    process.exit(1);
  }
}

build();
