/**
 * ビルドスクリプト
 * TypeScriptをGAS用にトランスパイルする（tscを使用）
 */
const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "dist");

// tscでトランスパイル（tsconfig.build.jsonを使用）
try {
  execSync("npx tsc -p tsconfig.build.json", { stdio: "inherit" });

  // 生成されたJSファイルにバナーを追加
  const files = fs.readdirSync(distDir).filter((f) => f.endsWith(".js"));
  for (const file of files) {
    const filePath = path.join(distDir, file);
    const content = fs.readFileSync(filePath, "utf8");
    const banner = "// Auto-generated by tsc - DO NOT EDIT\n";
    if (!content.startsWith(banner)) {
      fs.writeFileSync(filePath, banner + content);
    }
  }

  console.log("Build completed successfully!");
} catch (error) {
  console.error("Build failed:", error.message);
  process.exit(1);
}
